[package]
name = "shocovox-rs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
lldb = "0.0.11" # debugging
rand = "0.8.5"

# for benchamrking
timeit = "0.1.2"


# for example cpu_render
image = "0.24.6"
show-image = "0.13.1"
