[package]
name = "shocovox-rs"
version = "0.1.0"
edition = "2021"
authors = ["Dávid Tóth <toth.david.munka@gmail.com>"]
license = "MIT OR Apache-2.0"

[features]
default = []
raytracing = ["dep:image", "dep:show-image"]
serialization = ["dep:serde"]
bevy_wgpu = ["dep:bevy", "raytracing"]

[dependencies]
serde = { version = "1.0.183", features = ["derive"], optional = true }
bendy = { git = "https://github.com/davids91/bendy.git" , features = ["std", "serde"]}

# for example cpu_render
image = { version = "0.25.1", optional = true }
show-image = { version = "0.14.0", optional = true }

# for example bevy_wgpu
bevy = { version = "0.13.2", features = ["dynamic_linking"], optional = true}

# debugging
#linker = "/usr/bin/clang"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
[dev-dependencies]
lldb = "0.0.11"
rand = "0.8.5"
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "performance"
harness = false
